#!/usr/bin/env bash
# Installing nginx on a server and configuring a simple server

# Installing nginx
sudo apt install nginx -y

# Altering the server config to create a server
echo "
events {

}

http {
	server {
		listen 80;
		return 200 \"Holberton School\";
	}
}
"  | sudo tee /etc/nginx/nginx.conf

# Restarting the server with the new config
sudo nginx -s reload
