#!/usr/bin/env bash
# Installing nginx on a server and configuring a simple server

# Installing the server
sudo apt-get -y nginx

# Altering the server config to create a server
echo "
http {
	server {
		listen 80;
		return 200 \"Holberton School\";
	}
}
" > /etc/nginx/nginx.conf

# Restarting the server with the new config
nginx -s reload
