#!/usr/bin/env bash
# Adding a redirect

# Update all packages
sudo apt update && sudo apt upgrade

# Install Nginx
sudo apt install nginx -y

# Write data to nginx.conf
printf %s "
events {

}

http {
	server {
		listen 80;
		location = /redirect_me {
			return 301 https://google.com;
		}
		return 200 \"Holberton School\";
	}
}" | sudo tee /etc/nginx/nginx.conf

# Reload nginx
sudo nginx -s reload
		
