#!/usr/bin/env bash
# Creating a server with a redirect

# Updating all packages
sudo apt update && sudo apt upgrade

# Install Nginx
sudo apt install nginx -y

# Creating an index page
echo "Holberton School" | sudo tee /var/www/html/index.html

# Write data to nginx.conf
echo "
events {

}

http {
	server {
		listen 80;

		root /var/www/html;

		location =/redirect_me {
			return 301 https://google.com;
		}
	}
}" | sudo tee /etc/nginx/nginx.conf

# Reload nginx
sudo nginx -s reload
		
