#!/usr/bin/env bash
# Adding a redirec

# Install Nginx
sudo apt install nginx -y

# Write data to nginx.conf
echo "
events {

}

http {
	server {
		listen 80;
		location =/redirect_me {
			return 301 https://google.com;
		}
		
		location =/ {
			return 200 \"Holberton School\";
		}
	}
}" | sudo tee /etc/nginx/nginx.conf

# Reload nginx
sudo nginx -s reload
		
